#ddev-generated
# Simple template to demonstrate ddev-a11ywatch-standalone
services:
  ddev-a11ywatch-standalone:
    container_name: ddev-${DDEV_SITENAME}-a11ywatch
    hostname: ${DDEV_SITENAME}-a11ywatch
    image: a11ywatch/a11ywatch:${A11YWATCH_IMAGE:-latest}
    networks: [default, ddev_default]
    expose:
      - 3280
      - 9222
      - 50050
      - 50051
      - 50052
      - 50053
      - 50055
    environment:
      - COMPUTER_VISION_ENDPOINT=${COMPUTER_VISION_ENDPOINT:-""}
      - COMPUTER_VISION_SUBSCRIPTION_KEY=${COMPUTER_VISION_SUBSCRIPTION_KEY:-""}
      - PAGESPEED_API_KEY=${PAGESPEED_API_KEY:-""}
      - AI_DISABLED=${AI_DISABLED:-false}
      - SUPER_MODE=${SUPER_MODE:-true}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - a11ywatch:/usr/share/a11ywatch/data
      - ".:/mnt/ddev_config"

volumes:
  a11ywatch:
